baseURL: "http://0x3f.org"
locale: "zh-cn"
title: "晴耕雨讀"
copyright: "© 2007-2024 鬼马妖刀"
googleAnalytics: "UA-93233020-1"
theme: "minima"
defaultContentLanguage: zh-cn

pagination:
  pagerSize: 10

# languages:
# # Override language-specific configurations
#   en:
#     languageName: EN
#     weight: 1
    
#   zh-cn:
#     languageName: 简中
#     weight: 2
#     params:
#       greet: 你好 :)
#       author:
#         status: 目前住在地球 🌍
#         description: |
#           这是 Minima, 一个简洁的 Hugo 主题，移植自 [Hexo Minima](https://github.com/adisaktijrs/hexo-theme-minima)。
#           支持深色模式、多语言、数学公式、流程图、代码语法高亮，当然还有分类、标签、系列等等。

params:
  # greet: "喵 :)"
  greet: 胡为乎来哉!
  subtitle: ""
  switch: ["🌚", "🌝"]
  defaultTheme: system
  displayDate: true
  displayDescription: true
  selectable: true
  tagsTitle: 标签
  categoriesTitle: 分类
  # commentOnAllPosts: true

  author:
    name: "晴耕雨讀"
    avatar: /images/avatar.png
    status: 🚴 🐈 📚 💻 🤔
    description: |
      程序员，喜欢猫和折叠车。  
      巧者劳而智者忧，无能者无所求，饱食而遨游，泛若不系之舟。

  comment:
    enable: true
    provider: "utterances"
    disqus:
      shortname: "hugo-minima"
    utterances:
      repo: "xbot/blog-comments"
      issueTerm: "pathname"
      label: "comment"

  social:
    - name: "email"
      url: "mailto:donie.leigh@gmail.com"
    - name: "github"
      url: "https://github.com/xbot"
      svg: ""
    - name: "rss"
      url: "/index.xml"
      svg: ""

  math:
    enable: true
    provider: katex

  diagram:
    enable: true
    provider: mermaid

  search:
    enable: true
    provider: fuse
    title: 搜索
    placeholder: 输入关键词

    fuse:
    # See also https://fusejs.io
      keys:
        - title
        - permalink
        - summary
        - content
      distance: 100
      location: 0
      threshold: 0.6
      ignoreLocation: false
      isCaseSensitive: false
      includeScore: false
      includeMatches: false
      minMatchCharLength: 1
      shouldSort: true
      findAllMatches: false

menu:
  main:
    - identifier: home
      name: 主页
      weight: 1
    - identifier: posts
      name: 文章
      weight: 2
    - identifier: tags
      name: 标签
      weight: 3
    - identifier: about
      name: 关于
      weight: 4
    - identifier: search
      name: 🔍
      weight: 5

taxonomies:
  category: "categories"
  series: "series"
  tag: "tags"

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  highlight:
    lineNos: true
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

security:
  allowContent:
    - "^text/html$"
    - "^text/markdown$"
